import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const componentsPages: ExamplePageMeta[] = [
    {
        slug: "command-palette",
        section: "Components",
        group: "Navigation",
        title: "Command palette",
        description: "Keyboard-first search and command menus for jumping to pages and running actions.",
        status: "new",
        load: () => import("./command-palette/index.ts"),
    },
    {
        slug: "segmented-control",
        section: "Components",
        group: "Buttons",
        title: "Segmented control",
        description: "A row of mutually exclusive options with a sliding indicator, for views, filters and settings.",
        status: "new",
        load: () => import("./segmented-control/index.ts"),
    },
    {
        slug: "avatar-group",
        section: "Components",
        group: "Data display",
        title: "Avatar group",
        description: "Stacked avatars with an overflow count, and avatars that show who is online.",
        status: "new",
        load: () => import("./avatar-group/index.ts"),
    },
    {
        slug: "stat-card",
        section: "Components",
        group: "Data display",
        title: "Stat card",
        description: "Metric cards with trend badges and small inline charts for dashboards.",
        status: "new",
        load: () => import("./stat-card/index.ts"),
    },
    {
        slug: "file-tree",
        section: "Components",
        group: "Navigation",
        title: "File tree",
        description: "Nested lists of files and folders that expand and collapse, with full keyboard support.",
        status: "new",
        load: () => import("./file-tree/index.ts"),
    },
    {
        slug: "tag-input",
        section: "Components",
        group: "Form",
        title: "Tag input",
        description: "Fields for entering several values at once, as free-form tags or picked from a list.",
        status: "new",
        load: () => import("./tag-input/index.ts"),
    },
    {
        slug: "copy-button",
        section: "Components",
        group: "Buttons",
        title: "Copy button",
        description: "Buttons and fields that copy text to the clipboard and confirm that it worked.",
        status: "new",
        load: () => import("./copy-button/index.ts"),
    },
    {
        slug: "inline-edit",
        section: "Components",
        group: "Form",
        title: "Inline edit",
        description: "Text that turns into a field in place, for settings pages and document titles.",
        status: "new",
        load: () => import("./inline-edit/index.ts"),
    },
    // Pages moved from the old docs. Each keeps its old URL and takes over its old sidebar entry.
    {
        slug: "animated-button",
        section: "Components",
        group: "Buttons",
        title: "Animated button",
        description: "Buttons and a theme switch that use hover, press and click animations to give clear visual feedback.",
        load: () => import("./animated-button/index.ts"),
    },
    {
        slug: "normal-button",
        section: "Components",
        group: "Buttons",
        title: "Button",
        description: "Everyday buttons for common actions: plain solid and outline buttons, store badges, download and cart buttons, icon buttons and shaped buttons.",
        load: () => import("./normal-button/index.ts"),
    },
    {
        slug: "login-buttons",
        section: "Components",
        group: "Buttons",
        title: "Login button",
        description: "Sign in buttons for Google, Apple and other social providers, in filled and bordered styles.",
        load: () => import("./login-buttons/index.ts"),
    },
    {
        slug: "dropdown-button",
        section: "Components",
        group: "Buttons",
        title: "Dropdown button",
        description: "Split buttons whose arrow opens a menu of options, and the picked option becomes the main action.",
        load: () => import("./dropdown-button/index.ts"),
    },
    {
        slug: "calendar",
        section: "Components",
        group: "Data display",
        title: "Calendar",
        description: "Month calendars, single date and range pickers, and an event calendar you can drop into forms and dashboards.",
        load: () => import("./calendar/index.ts"),
    },
    {
        slug: "tooltip",
        section: "Components",
        group: "Data display",
        title: "Tooltip",
        description: "Tooltips that show a short hint or a small card next to a button or picture on hover, focus or click.",
        notice: "Check the `z-index` values after you paste a tooltip into your project, so it shows above nearby content. Adjust the colors and spacing to match your design.",
        load: () => import("./tooltip/index.ts"),
    },
    {
        slug: "badge",
        section: "Components",
        group: "Data display",
        title: "Badge",
        description: "Small markers on icons and avatars that show counts, new activity, online status or verification.",
        load: () => import("./badge/index.ts"),
    },
    {
        slug: "timeline",
        section: "Components",
        group: "Data display",
        title: "Timeline",
        description: "Vertical, alternating and icon timelines for project milestones, work logs and career history.",
        load: () => import("./timeline/index.ts"),
    },
    {
        slug: "github-activity-graph",
        section: "Components",
        group: "Data display",
        title: "GitHub activity graph",
        description: "GitHub style contribution grids that show daily activity over a year, with hover tooltips and a color legend.",
        load: () => import("./github-activity-graph/index.ts"),
    },
    {
        slug: "graph-chart",
        section: "Components",
        group: "Data display",
        title: "Graph chart",
        description: "Animated SVG line, bar and area charts with labeled axes, built with framer-motion and no chart library.",
        load: () => import("./graph-chart/index.ts"),
    },
    {
        slug: "redo-undo",
        section: "Components",
        group: "Data display",
        title: "Undo and redo",
        description: "Text editors that keep their own undo history, with undo and redo from buttons, keyboard shortcuts or both.",
        load: () => import("./redo-undo/index.ts"),
    },
    {
        slug: "table",
        section: "Components",
        group: "Data display",
        title: "Table",
        description: "Data tables with search, column sorting, row action menus, pagination and row selection for bulk actions.",
        load: () => import("./table/index.ts"),
    },
    {
        slug: "pie-chart",
        section: "Components",
        group: "Data display",
        title: "Pie chart",
        description: "SVG pie and donut charts with percentage labels and a legend. Pass the categories and values, and the chart works out each slice's share of the whole.",
        load: () => import("./pie-chart/index.ts"),
    },
    {
        slug: "product-card",
        section: "Components",
        group: "E-commerce",
        title: "Product card",
        description: "Product cards for online stores, from clothing, grocery and digital goods cards to compact rows for product lists.",
        load: () => import("./product-card/index.ts"),
    },
    {
        slug: "ads-card",
        section: "Components",
        group: "E-commerce",
        title: "Ads card",
        description: "Product ads and promo banners for online stores, each taking its own image, copy and call to action.",
        load: () => import("./ads-card/index.ts"),
    },
    {
        slug: "loader",
        section: "Components",
        group: "Feedback",
        title: "Loader",
        description: "Animated loading indicators, from simple spinning rings to dot, wave and tile patterns, that show content is on its way.",
        load: () => import("./loader/index.ts"),
    },
    {
        slug: "skeleton",
        section: "Components",
        group: "Feedback",
        title: "Skeleton",
        description: "Loading placeholders that match the shape of cards, galleries, posts and product pages while their content loads.",
        load: () => import("./skeleton/index.ts"),
    },
    {
        slug: "testimonials",
        section: "Components",
        group: "Feedback",
        title: "Testimonial",
        description: "Testimonial cards that show customer quotes, the author and an optional star rating on landing and product pages.",
        load: () => import("./testimonials/index.ts"),
    },
    {
        slug: "notification",
        section: "Components",
        group: "Feedback",
        title: "Notification",
        description: "Notifications that slide in to confirm actions, report errors and show status, with a progress bar, auto close and a close button.",
        notice: "These notifications give you the structure only. Adjust `z-index` and `position` to fit your layout, and control `open` from the part of your app that triggers them.",
        load: () => import("./notification/index.ts"),
    },
    {
        slug: "toast",
        section: "Components",
        group: "Feedback",
        title: "Toast",
        description: "Short notifications that slide in at a corner of the screen, can be called from anywhere, and dismiss themselves after a few seconds.",
        load: () => import("./toast/index.ts"),
    },
    {
        slug: "alert-message",
        section: "Components",
        group: "Feedback",
        title: "Alert",
        description: "Inline alert messages for success, info, error and warning states, with background, title, border and dismissible styles.",
        load: () => import("./alert-message/index.ts"),
    },
    {
        slug: "tree-dropdown",
        section: "Components",
        group: "Feedback",
        title: "Tree dropdown",
        description: "Collapsible trees for showing nested data such as departments, folders and files, or a checkable hierarchy.",
        notice: "These trees render nested nodes with recursion, which can be harder to follow if you are new to React. The comments in the code explain each step.",
        load: () => import("./tree-dropdown/index.ts"),
    },
    {
        slug: "context-menu",
        section: "Components",
        group: "Feedback",
        title: "Context menu",
        description: "Right-click menus that open at the pointer and list actions for the item under it.",
        load: () => import("./context-menu/index.ts"),
    },
    {
        slug: "dialog-message",
        section: "Components",
        group: "Feedback",
        title: "Dialog",
        description: "Modal dialogs for picking an option or confirming a critical action.",
        load: () => import("./dialog-message/index.ts"),
    },
    {
        slug: "input-text",
        section: "Components",
        group: "Form",
        title: "Input",
        description: "Text inputs for forms: labeled, floating label, icon, password, URL, price, search, subscribe and phone number fields.",
        load: () => import("./input-text/index.ts"),
    },
    {
        slug: "input-select",
        section: "Components",
        group: "Form",
        title: "Select",
        description: "Select menus for picking one or more options from a list, with optional icons, a search field and badges for the picked options.",
        load: () => import("./input-select/index.ts"),
    },
    {
        slug: "strong-password",
        section: "Components",
        group: "Form",
        title: "Strong password",
        description: "Password fields that check a new password against your rules as it is typed, with a message, a meter or a checklist.",
        load: () => import("./strong-password/index.ts"),
    },
    {
        slug: "input-file",
        section: "Components",
        group: "Form",
        title: "File input",
        description: "File upload fields for images and profile pictures, with a preview of the picked file.",
        load: () => import("./input-file/index.ts"),
    },
    {
        slug: "input-checkbox",
        section: "Components",
        group: "Form",
        title: "Checkbox",
        description: "Custom drawn checkboxes for single options and lists, built on a native input so keyboards and screen readers still work.",
        notice: "The checked color comes from the `color` prop (default `#3B9DF8`). To change the size, adjust the `width` and `height` of the SVG box.",
        load: () => import("./input-checkbox/index.ts"),
    },
    {
        slug: "input-number",
        section: "Components",
        group: "Form",
        title: "Number input",
        description: "Number fields with minus and plus buttons for adjusting quantities, counts and other small values.",
        load: () => import("./input-number/index.ts"),
    },
    {
        slug: "input-switch",
        section: "Components",
        group: "Form",
        title: "Switch",
        description: "Toggle switches in round, square and stretching styles, each in four sizes, for turning a setting on or off.",
        load: () => import("./input-switch/index.ts"),
    },
    {
        slug: "input-textarea",
        section: "Components",
        group: "Form",
        title: "Textarea",
        description: "Multi-line text fields for longer answers such as descriptions, messages and feedback.",
        load: () => import("./input-textarea/index.ts"),
    },
    {
        slug: "input-radio",
        section: "Components",
        group: "Form",
        title: "Radio",
        description: "Styled radio buttons for choosing one option from a set.",
        load: () => import("./input-radio/index.ts"),
    },
    {
        slug: "input-range",
        section: "Components",
        group: "Form",
        title: "Range",
        description: "Sliders for picking a number within a range, either freely or snapped to set breakpoints.",
        load: () => import("./input-range/index.ts"),
    },
    {
        slug: "otp-input",
        section: "Components",
        group: "Form",
        title: "OTP input",
        description: "Digit-by-digit code inputs for one-time passwords and verification codes.",
        load: () => import("./otp-input/index.ts"),
    },
    {
        slug: "modal",
        section: "Components",
        group: "Navigation",
        title: "Modal",
        description: "Modals for confirmations, notices, consent requests, sign in forms and delete checks that open over the page with a scale or slide animation.",
        notice: "Each modal is controlled. Keep an `open` state in your component, set it from your own trigger button and pass `onClose` so the modal can close itself.",
        load: () => import("./modal/index.ts"),
    },
    {
        slug: "tabs",
        section: "Components",
        group: "Navigation",
        title: "Tabs",
        description: "Tab lists in several styles for switching between sections or views, with keyboard support and a selected value you can control.",
        load: () => import("./tabs/index.ts"),
    },
    {
        slug: "timer",
        section: "Components",
        group: "Navigation",
        title: "Timer",
        description: "Countdown timers that tick down to a date, for sales, launches and events, in six visual styles.",
        load: () => import("./timer/index.ts"),
    },
    {
        slug: "breadcrumb",
        section: "Components",
        group: "Navigation",
        title: "Breadcrumb",
        description: "Breadcrumbs that show where the current page sits in your site, as plain text, links, a collapsible dropdown, tinted bars or a page header with a back button.",
        load: () => import("./breadcrumb/index.ts"),
    },
    {
        slug: "chip",
        section: "Components",
        group: "Navigation",
        title: "Chip",
        description: "Compact chips for tags, statuses and people, with sizes, styles, icons, avatars and an optional remove button.",
        load: () => import("./chip/index.ts"),
    },
    {
        slug: "progress-bar",
        section: "Components",
        group: "Navigation",
        title: "Progress bar",
        description: "Linear, circular and striped progress bars that show how far a task has come.",
        load: () => import("./progress-bar/index.ts"),
    },
    {
        slug: "rating",
        section: "Components",
        group: "Navigation",
        title: "Rating",
        description: "Star, card and number based rating inputs for collecting scores and feedback.",
        load: () => import("./rating/index.ts"),
    },
    {
        slug: "pagination",
        section: "Components",
        group: "Navigation",
        title: "Pagination",
        description: "Page navigation controls for moving through lists and results split across pages.",
        load: () => import("./pagination/index.ts"),
    },
    {
        slug: "stepper",
        section: "Components",
        group: "Navigation",
        title: "Stepper",
        description: "Step indicators that show where a user is in a multi-step flow such as checkout or onboarding.",
        load: () => import("./stepper/index.ts"),
    },
    {
        slug: "marquee",
        section: "Components",
        group: "Navigation",
        title: "Marquee",
        description: "Rows and columns of links that scroll in a continuous loop and pause on hover.",
        load: () => import("./marquee/index.ts"),
    },
    {
        slug: "slider",
        section: "Components",
        group: "Other",
        title: "Slider",
        description: "A hero slider for featured content, built with Swiper.",
        notice: "Install the `swiper` package before using the slider. Without it the slider does not work.",
        unlisted: true,
        load: () => import("./slider/index.ts"),
    },
    {
        slug: "snippet",
        section: "Components",
        group: "Other",
        title: "Snippet",
        description: "Short command snippets, such as install commands, with an optional button that copies the command.",
        load: () => import("./snippet/index.ts"),
    },
    {
        slug: "code",
        section: "Components",
        group: "Other",
        title: "Code block",
        description: "A simple gray code block for showing commands and short snippets.",
        load: () => import("./code/index.ts"),
    },
    {
        slug: "cards",
        section: "Components",
        group: "Surfaces",
        title: "Cards",
        description: "Content cards for profiles, products, pricing, events, posts and media, each built as a reusable component you fill with your own data.",
        load: () => import("./cards/index.ts"),
    },
    {
        slug: "animated-cards",
        section: "Components",
        group: "Surfaces",
        title: "Animated cards",
        description: "Cards with hover effects such as image zoom, 3D flip, color fill and a cursor spotlight, for portfolios, blogs, teams and product grids.",
        load: () => import("./animated-cards/index.ts"),
    },
    {
        slug: "image-gallery",
        section: "Components",
        group: "Surfaces",
        title: "Image gallery",
        description: "Grid layouts for showing a set of photos, from a plain three column grid to mosaic and bento layouts with wide and tall tiles.",
        load: () => import("./image-gallery/index.ts"),
    },
    {
        slug: "drag-and-drop",
        section: "Components",
        group: "Surfaces",
        title: "Drag and drop",
        description: "Drag and drop grids, lists, file drop zones and a todo board for reordering items and uploading files.",
        load: () => import("./drag-and-drop/index.ts"),
    },
    {
        slug: "drawer",
        section: "Components",
        group: "Surfaces",
        title: "Drawer",
        description: "Panels that slide in from an edge of the screen to show extra content or actions without leaving the page.",
        notice: "Each drawer is controlled by your own state. Keep an `open` value in the parent, set it to true from a button on your page and pass `open` and `onClose` to the drawer. It closes on Escape and on a click outside the panel.",
        load: () => import("./drawer/index.ts"),
    },
    {
        slug: "according",
        section: "Components",
        group: "Surfaces",
        title: "Accordion",
        description: "Stacked sections that expand and collapse so readers can open one answer or detail at a time.",
        load: () => import("./according/index.ts"),
    },
    {
        slug: "appbar",
        section: "Components",
        group: "Surfaces",
        title: "App bar",
        description: "Top bars for an app header with a logo, a menu button, search and icon buttons with count badges.",
        load: () => import("./appbar/index.ts"),
    },
    {
        slug: "carousel",
        section: "Components",
        group: "Surfaces",
        title: "Carousel",
        description: "Image carousels with arrow controls, autoplay, or a slow cross fade between slides.",
        load: () => import("./carousel/index.ts"),
    },
    {
        slug: "comparison-card",
        section: "Components",
        group: "Surfaces",
        title: "Comparison card",
        description: "Before and after image comparisons with a divider you drag to reveal more of either image.",
        load: () => import("./comparison-card/index.ts"),
    },
    {
        slug: "resizable-layout",
        section: "Components",
        group: "Other",
        title: "Resizable layout",
        description: "A two panel layout with a divider you drag to resize the left panel.",
        unlisted: true,
        load: () => import("./resizable-layout/index.ts"),
    },
    {
        slug: "image-cropper",
        section: "Components",
        group: "Surfaces",
        title: "Image cropper",
        description: "An image upload area that opens a modal where you move and resize a crop box before saving the cropped image.",
        load: () => import("./image-cropper/index.ts"),
    },
];
