import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const componentsPages: ExamplePageMeta[] = [
    {
        slug: "command-palette",
        section: "Components",
        group: "Navigation",
        title: "Command palette",
        description: "Keyboard-first search and command menus for jumping to pages and running actions.",
        status: "new",
        load: () => import("./command-palette/index.ts"),
    },
    {
        slug: "segmented-control",
        section: "Components",
        group: "Buttons",
        title: "Segmented control",
        description: "A row of mutually exclusive options with a sliding indicator, for views, filters and settings.",
        status: "new",
        load: () => import("./segmented-control/index.ts"),
    },
    {
        slug: "avatar-group",
        section: "Components",
        group: "Data display",
        title: "Avatar group",
        description: "Stacked avatars with an overflow count, and avatars that show who is online.",
        status: "new",
        load: () => import("./avatar-group/index.ts"),
    },
    {
        slug: "stat-card",
        section: "Components",
        group: "Data display",
        title: "Stat card",
        description: "Metric cards with trend badges and small inline charts for dashboards.",
        status: "new",
        load: () => import("./stat-card/index.ts"),
    },
    {
        slug: "file-tree",
        section: "Components",
        group: "Navigation",
        title: "File tree",
        description: "Nested lists of files and folders that expand and collapse, with full keyboard support.",
        status: "new",
        load: () => import("./file-tree/index.ts"),
    },
    {
        slug: "tag-input",
        section: "Components",
        group: "Form",
        title: "Tag input",
        description: "Fields for entering several values at once, as free-form tags or picked from a list.",
        status: "new",
        load: () => import("./tag-input/index.ts"),
    },
    {
        slug: "copy-button",
        section: "Components",
        group: "Buttons",
        title: "Copy button",
        description: "Buttons and fields that copy text to the clipboard and confirm that it worked.",
        status: "new",
        load: () => import("./copy-button/index.ts"),
    },
    {
        slug: "inline-edit",
        section: "Components",
        group: "Form",
        title: "Inline edit",
        description: "Text that turns into a field in place, for settings pages and document titles.",
        status: "new",
        load: () => import("./inline-edit/index.ts"),
    },
];
