import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const blocksPages: ExamplePageMeta[] = [
    {
        slug: "feature-sections",
        section: "Blocks",
        group: "Marketing",
        title: "Feature sections",
        description: "Bento grids, tabbed feature previews and an integrations directory for product landing pages.",
        status: "new",
        load: () => import("./feature-sections/index.ts"),
    },
    {
        slug: "social-proof",
        section: "Blocks",
        group: "Marketing",
        title: "Testimonials and logos",
        description: "Customer quotes, logo clouds and stats that show who uses your product.",
        status: "new",
        load: () => import("./social-proof/index.ts"),
    },
    {
        slug: "faq-sections",
        section: "Blocks",
        group: "Marketing",
        title: "FAQ sections",
        description: "Searchable question and answer sections grouped by topic.",
        status: "new",
        load: () => import("./faq-sections/index.ts"),
    },
    {
        slug: "cta-sections",
        section: "Blocks",
        group: "Marketing",
        title: "CTA and waitlist",
        description: "Closing calls to action and a pre-launch waitlist with a countdown.",
        status: "new",
        load: () => import("./cta-sections/index.ts"),
    },
    {
        slug: "comparison-table",
        section: "Blocks",
        group: "Marketing",
        title: "Comparison table",
        description: "A plan-by-plan feature table to place below pricing cards.",
        status: "new",
        load: () => import("./comparison-table/index.ts"),
    },
    {
        slug: "team-sections",
        section: "Blocks",
        group: "Marketing",
        title: "Team sections",
        description: "Team member cards for about and careers pages.",
        status: "new",
        load: () => import("./team-sections/index.ts"),
    },
    {
        slug: "blog-sections",
        section: "Blocks",
        group: "Content",
        title: "Blog and changelog",
        description: "Article card grids and a release timeline for content and product update pages.",
        status: "new",
        load: () => import("./blog-sections/index.ts"),
    },
    {
        slug: "authentication",
        section: "Blocks",
        group: "Authentication",
        title: "Sign in and sign up",
        description: "Sign-in and sign-up screens with social buttons, validation and confirmation states.",
        status: "new",
        load: () => import("./authentication/index.ts"),
    },
    {
        slug: "application-shells",
        section: "Blocks",
        group: "Application",
        title: "Dashboard and settings",
        description: "App layouts with a sidebar dashboard and an account settings page.",
        status: "new",
        load: () => import("./application-shells/index.ts"),
    },
    // Pages moved from the old docs. Each keeps its old URL and takes over its old sidebar entry.
    {
        slug: "offer-grid",
        section: "Blocks",
        group: "E-commerce",
        title: "Offer grid",
        description: "Promotion grids and banners for store home pages that highlight categories, deals and single products.",
        load: () => import("./offer-grid/index.ts"),
    },
    {
        slug: "product-details-page",
        section: "Blocks",
        group: "E-commerce",
        title: "Product details",
        description: "Product detail pages that bring images, options, pricing and purchase actions together to support a buying decision.",
        load: () => import("./product-details-page/index.ts"),
    },
    {
        slug: "checkout-page",
        section: "Blocks",
        group: "E-commerce",
        title: "Checkout",
        description: "Full checkout page layouts that collect billing, contact and payment details next to an order summary.",
        load: () => import("./checkout-page/index.ts"),
    },
    {
        slug: "product-filter-page",
        section: "Blocks",
        group: "Other",
        title: "Product filter",
        description: "A shop listing with sidebar filters, search and sorting over a product grid.",
        unlisted: true,
        load: () => import("./product-filter-page/index.ts"),
    },
    {
        slug: "empty-page",
        section: "Blocks",
        group: "Empty states",
        title: "Empty page",
        description: "Empty state cards with an illustration and a short message for lists, inboxes and searches that have nothing to show yet.",
        load: () => import("./empty-page/index.ts"),
    },
    {
        slug: "404-page",
        section: "Blocks",
        group: "Empty states",
        title: "404 page",
        description: "404 page cards that tell people the link is broken and send them back to the homepage.",
        load: () => import("./404-page/index.ts"),
    },
    {
        slug: "newsletter-form",
        section: "Blocks",
        group: "Forms",
        title: "Newsletter form",
        description: "Newsletter signup sections with an email field and a subscribe button, from a compact centered form to full sections with illustrations.",
        load: () => import("./newsletter-form/index.ts"),
    },
    {
        slug: "contact-form",
        section: "Blocks",
        group: "Forms",
        title: "Contact form",
        description: "Contact form sections for collecting a name, email and message, with layouts for a plain page, a dark card, a map and a contact details panel.",
        load: () => import("./contact-form/index.ts"),
    },
    {
        slug: "multi-step-form",
        section: "Blocks",
        group: "Forms",
        title: "Multi-step form",
        description: "Forms split into steps with a progress bar, so long sign-ups and applications can be filled in one section at a time.",
        load: () => import("./multi-step-form/index.ts"),
    },
    {
        slug: "responsive-footer",
        section: "Blocks",
        group: "Sections",
        title: "Footer",
        description: "Responsive footers with link columns, contact details, newsletter fields and social icons that stack cleanly on small screens.",
        load: () => import("./responsive-footer/index.ts"),
    },
    {
        slug: "responsive-search-bar",
        section: "Blocks",
        group: "Other",
        title: "Search bar",
        description: "Search fields that open a dropdown panel with results, recent searches, filters and quick actions.",
        load: () => import("./responsive-search-bar/index.ts"),
    },
    {
        slug: "responsive-sidebar",
        section: "Blocks",
        group: "Other",
        title: "Sidebar",
        description: "Responsive sidebars that collapse to an icon rail with tooltips, with sections, dropdown items, a profile footer or a theme switch.",
        load: () => import("./responsive-sidebar/index.ts"),
    },
    {
        slug: "hero-section",
        section: "Blocks",
        group: "Sections",
        title: "Hero",
        description: "Hero sections for the top of a landing page, with a headline, supporting text, calls to action or search, and a large image.",
        load: () => import("./hero-section/index.ts"),
    },
    {
        slug: "pricing-section",
        section: "Blocks",
        group: "Sections",
        title: "Pricing",
        description: "Pricing sections that lay out plans side by side with prices, feature lists and a billing switch.",
        load: () => import("./pricing-section/index.ts"),
    },
    {
        slug: "responsive-navbar",
        section: "Blocks",
        group: "Sections",
        title: "Navbar",
        description: "Responsive navigation bars with links, search, mega menus and an account dropdown that collapse into a menu on small screens.",
        notice: "The mobile menus use `absolute` positioning so they stay inside the preview. In your project, use `fixed` so the navbar and its menu stay in place while the page scrolls.",
        load: () => import("./responsive-navbar/index.ts"),
    },
];
