import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const blocksPages: ExamplePageMeta[] = [
    {
        slug: "feature-sections",
        section: "Blocks",
        group: "Marketing",
        title: "Feature sections",
        description: "Bento grids, tabbed feature previews and an integrations directory for product landing pages.",
        status: "new",
        load: () => import("./feature-sections/index.ts"),
    },
    {
        slug: "social-proof",
        section: "Blocks",
        group: "Marketing",
        title: "Testimonials and logos",
        description: "Customer quotes, logo clouds and stats that show who uses your product.",
        status: "new",
        load: () => import("./social-proof/index.ts"),
    },
    {
        slug: "faq-sections",
        section: "Blocks",
        group: "Marketing",
        title: "FAQ sections",
        description: "Searchable question and answer sections grouped by topic.",
        status: "new",
        load: () => import("./faq-sections/index.ts"),
    },
    {
        slug: "cta-sections",
        section: "Blocks",
        group: "Marketing",
        title: "CTA and waitlist",
        description: "Closing calls to action and a pre-launch waitlist with a countdown.",
        status: "new",
        load: () => import("./cta-sections/index.ts"),
    },
    {
        slug: "comparison-table",
        section: "Blocks",
        group: "Marketing",
        title: "Comparison table",
        description: "A plan-by-plan feature table to place below pricing cards.",
        status: "new",
        load: () => import("./comparison-table/index.ts"),
    },
    {
        slug: "team-sections",
        section: "Blocks",
        group: "Marketing",
        title: "Team sections",
        description: "Team member cards for about and careers pages.",
        status: "new",
        load: () => import("./team-sections/index.ts"),
    },
    {
        slug: "blog-sections",
        section: "Blocks",
        group: "Content",
        title: "Blog and changelog",
        description: "Article card grids and a release timeline for content and product update pages.",
        status: "new",
        load: () => import("./blog-sections/index.ts"),
    },
    {
        slug: "authentication",
        section: "Blocks",
        group: "Authentication",
        title: "Sign in and sign up",
        description: "Sign-in and sign-up screens with social buttons, validation and confirmation states.",
        status: "new",
        load: () => import("./authentication/index.ts"),
    },
    {
        slug: "application-shells",
        section: "Blocks",
        group: "Application",
        title: "Dashboard and settings",
        description: "App layouts with a sidebar dashboard and an account settings page.",
        status: "new",
        load: () => import("./application-shells/index.ts"),
    },
];
