import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const animationsPages: ExamplePageMeta[] = [
    {
        slug: "number-ticker",
        section: "Animations",
        group: "Text",
        title: "Number ticker",
        description: "Animated counters and a flip countdown for stats, prices and launch pages.",
        status: "new",
        load: () => import("./number-ticker/index.ts"),
    },
    {
        slug: "glow-cards",
        section: "Animations",
        group: "Cards",
        title: "Glow cards",
        description: "Cards with a pointer spotlight or a light beam that travels around the border.",
        status: "new",
        load: () => import("./glow-cards/index.ts"),
    },
    {
        slug: "tilt-card",
        section: "Animations",
        group: "Cards",
        title: "Tilt card",
        description: "Cards that tilt toward the pointer with a moving glare or layered parallax.",
        status: "new",
        load: () => import("./tilt-card/index.ts"),
    },
    {
        slug: "dock",
        section: "Animations",
        group: "Layouts",
        title: "Magnifying dock",
        description: "A dock of app icons that grow as the pointer moves across them.",
        status: "new",
        load: () => import("./dock/index.ts"),
    },
    {
        slug: "expandable-card",
        section: "Animations",
        group: "Layouts",
        title: "Expandable card",
        description: "Cards that grow into a detail dialog with shared layout animations.",
        status: "new",
        load: () => import("./expandable-card/index.ts"),
    },
    {
        slug: "animated-list",
        section: "Animations",
        group: "Layouts",
        title: "Animated list",
        description: "A live feed where new items slide in and push older ones down.",
        status: "new",
        load: () => import("./animated-list/index.ts"),
    },
    {
        slug: "interactive-buttons",
        section: "Animations",
        group: "Buttons",
        title: "Interactive buttons",
        description: "Buttons with shimmer, ripple, confetti and press-and-hold feedback.",
        status: "new",
        load: () => import("./interactive-buttons/index.ts"),
    },
    {
        slug: "animated-beam",
        section: "Animations",
        group: "Visuals",
        title: "Animated beam",
        description: "Light pulses traveling along lines that connect icons, for integration and data flow diagrams.",
        status: "new",
        load: () => import("./animated-beam/index.ts"),
    },
    {
        slug: "ambient-backgrounds",
        section: "Animations",
        group: "Visuals",
        title: "Ambient backgrounds",
        description: "Meteor and dot grid backgrounds for hero sections and announcements.",
        status: "new",
        load: () => import("./ambient-backgrounds/index.ts"),
    },
    {
        slug: "word-rotate",
        section: "Animations",
        group: "Text",
        title: "Word rotate",
        description: "Headlines where one word changes on a timer with a letter by letter transition.",
        status: "new",
        load: () => import("./word-rotate/index.ts"),
    },
    {
        slug: "text-animations",
        section: "Animations",
        group: "Text",
        title: "Text animations",
        description: "Headline and paragraph animations: blur in, split letters, highlight sweeps and more.",
        status: "new",
        load: () => import("./text-animations/index.ts"),
    },
    {
        slug: "scroll-animations",
        section: "Animations",
        group: "Visuals",
        title: "Scroll animations",
        description: "Effects driven by scroll position, such as reveals, sticky steps and progress.",
        status: "new",
        load: () => import("./scroll-animations/index.ts"),
    },
    {
        slug: "cursor-effects",
        section: "Animations",
        group: "Visuals",
        title: "Cursor effects",
        description: "Pointer followers, trails and magnetic areas for interactive sections.",
        status: "new",
        load: () => import("./cursor-effects/index.ts"),
    },
    {
        slug: "flip-cards",
        section: "Animations",
        group: "Cards",
        title: "Flip cards",
        description: "Cards that flip, unfold or reveal a back side on hover, click or focus.",
        status: "new",
        load: () => import("./flip-cards/index.ts"),
    },
    {
        slug: "micro-interactions",
        section: "Animations",
        group: "Buttons",
        title: "Micro-interactions",
        description: "Small animated controls: toggles, like buttons, checkboxes and morphing icons.",
        status: "new",
        load: () => import("./micro-interactions/index.ts"),
    },
    {
        slug: "animated-charts",
        section: "Animations",
        group: "Visuals",
        title: "Animated charts",
        description: "Bar, line and donut charts that animate in and respond to hover.",
        status: "new",
        load: () => import("./animated-charts/index.ts"),
    },
];
