import type {ExamplePageMeta} from "../types.ts";

// Pages in this section. Each entry loads its examples from ./<slug>/index.ts on demand.
export const animationsPages: ExamplePageMeta[] = [
    {
        slug: "paper-effects",
        section: "Animations",
        group: "Cards",
        title: "Paper effects",
        description: "A peelable sticker, an opening envelope, a scratch card, a tear-off ticket stub and a developing instant photo.",
        status: "new",
        load: () => import("./paper-effects/index.ts"),
    },
    {
        slug: "physics-playground",
        section: "Animations",
        group: "Visuals",
        title: "Physics playground",
        description: "Hand-written physics: swinging tags on strings, falling letters, sloshing liquid, pluckable strings and bubble wrap.",
        status: "new",
        load: () => import("./physics-playground/index.ts"),
    },
    {
        slug: "retro-displays",
        section: "Animations",
        group: "Text",
        title: "Retro displays",
        description: "A split-flap board, a Nixie tube clock, an LED dot-matrix sign, a CRT terminal and a phosphor oscilloscope.",
        status: "new",
        load: () => import("./retro-displays/index.ts"),
    },
    {
        slug: "number-ticker",
        section: "Animations",
        group: "Text",
        title: "Number ticker",
        description: "Animated counters and a flip countdown for stats, prices and launch pages.",
        status: "new",
        load: () => import("./number-ticker/index.ts"),
    },
    {
        slug: "glow-cards",
        section: "Animations",
        group: "Cards",
        title: "Glow cards",
        description: "Cards with a pointer spotlight or a light beam that travels around the border.",
        status: "new",
        load: () => import("./glow-cards/index.ts"),
    },
    {
        slug: "tilt-card",
        section: "Animations",
        group: "Cards",
        title: "Tilt card",
        description: "Cards that tilt toward the pointer with a moving glare or layered parallax.",
        status: "new",
        load: () => import("./tilt-card/index.ts"),
    },
    {
        slug: "dock",
        section: "Animations",
        group: "Layouts",
        title: "Magnifying dock",
        description: "A dock of app icons that grow as the pointer moves across them.",
        status: "new",
        load: () => import("./dock/index.ts"),
    },
    {
        slug: "expandable-card",
        section: "Animations",
        group: "Layouts",
        title: "Expandable card",
        description: "Cards that grow into a detail dialog with shared layout animations.",
        status: "new",
        load: () => import("./expandable-card/index.ts"),
    },
    {
        slug: "animated-list",
        section: "Animations",
        group: "Layouts",
        title: "Animated list",
        description: "A live feed where new items slide in and push older ones down.",
        status: "new",
        load: () => import("./animated-list/index.ts"),
    },
    {
        slug: "interactive-buttons",
        section: "Animations",
        group: "Buttons",
        title: "Interactive buttons",
        description: "Buttons with shimmer, ripple, confetti and press-and-hold feedback.",
        status: "new",
        load: () => import("./interactive-buttons/index.ts"),
    },
    {
        slug: "animated-beam",
        section: "Animations",
        group: "Visuals",
        title: "Animated beam",
        description: "Light pulses traveling along lines that connect icons, for integration and data flow diagrams.",
        status: "new",
        load: () => import("./animated-beam/index.ts"),
    },
    {
        slug: "ambient-backgrounds",
        section: "Animations",
        group: "Visuals",
        title: "Ambient backgrounds",
        description: "Meteor and dot grid backgrounds for hero sections and announcements.",
        status: "new",
        load: () => import("./ambient-backgrounds/index.ts"),
    },
    {
        slug: "word-rotate",
        section: "Animations",
        group: "Text",
        title: "Word rotate",
        description: "Headlines where one word changes on a timer with a letter by letter transition.",
        status: "new",
        load: () => import("./word-rotate/index.ts"),
    },
    {
        slug: "text-animations",
        section: "Animations",
        group: "Text",
        title: "Text animations",
        description: "Headline and paragraph animations: blur in, split letters, highlight sweeps and more.",
        status: "new",
        load: () => import("./text-animations/index.ts"),
    },
    {
        slug: "scroll-animations",
        section: "Animations",
        group: "Visuals",
        title: "Scroll animations",
        description: "Effects driven by scroll position, such as reveals, sticky steps and progress.",
        status: "new",
        load: () => import("./scroll-animations/index.ts"),
    },
    {
        slug: "cursor-effects",
        section: "Animations",
        group: "Visuals",
        title: "Cursor effects",
        description: "Pointer followers, trails and magnetic areas for interactive sections.",
        status: "new",
        load: () => import("./cursor-effects/index.ts"),
    },
    {
        slug: "flip-cards",
        section: "Animations",
        group: "Cards",
        title: "Flip cards",
        description: "Cards that flip, unfold or reveal a back side on hover, click or focus.",
        status: "new",
        load: () => import("./flip-cards/index.ts"),
    },
    {
        slug: "micro-interactions",
        section: "Animations",
        group: "Buttons",
        title: "Micro-interactions",
        description: "Small animated controls: toggles, like buttons, checkboxes and morphing icons.",
        status: "new",
        load: () => import("./micro-interactions/index.ts"),
    },
    {
        slug: "animated-charts",
        section: "Animations",
        group: "Visuals",
        title: "Animated charts",
        description: "Bar, line and donut charts that animate in and respond to hover.",
        status: "new",
        load: () => import("./animated-charts/index.ts"),
    },
    // Pages moved from the old docs. Each keeps its old URL and takes over its old sidebar entry.
    {
        slug: "reaction-trail",
        section: "Animations",
        group: "Buttons",
        title: "Reaction trail",
        description: "Social post cards with a Like button that opens an animated reaction picker on hover or focus.",
        load: () => import("./reaction-trail/index.ts"),
    },
    {
        slug: "hover-effects",
        section: "Animations",
        group: "Buttons",
        title: "Hover effects",
        description: "Hover cards that follow the pointer, for avatar tooltips and link previews.",
        load: () => import("./hover-effects/index.ts"),
    },
    {
        slug: "magic-card",
        section: "Animations",
        group: "Cards",
        title: "Magic card",
        description: "Cards that react to the pointer with a following preview panel, a 3D tilt with a spotlight, or layered parallax movement.",
        load: () => import("./magic-card/index.ts"),
    },
    {
        slug: "reveal-card",
        section: "Animations",
        group: "Cards",
        title: "Reveal card",
        description: "List rows that slide aside when swiped to reveal an action on either side, with basic, elastic and rotating motion.",
        load: () => import("./reveal-card/index.ts"),
    },
    {
        slug: "magnet-card",
        section: "Animations",
        group: "Cards",
        title: "Magnet card",
        description: "Cards that are pulled toward the cursor and tilt while hovered, for projects, products and feature highlights.",
        load: () => import("./magnet-card/index.ts"),
    },
    {
        slug: "animated-accordion",
        section: "Animations",
        group: "Layouts",
        title: "Accordion",
        description: "Animated accordions that open image panels or text sections with staggered motion.",
        load: () => import("./animated-accordion/index.ts"),
    },
    {
        slug: "drag-animations",
        section: "Animations",
        group: "Layouts",
        title: "Drag",
        description: "Drag interactions for reordering cards, locking drag direction and swiping through a card stack.",
        load: () => import("./drag-animations/index.ts"),
    },
    {
        slug: "sorting-animation",
        section: "Animations",
        group: "Layouts",
        title: "Sorting",
        description: "Sorting animations that move items to their new place when a list is shuffled, filtered or sorted.",
        load: () => import("./sorting-animation/index.ts"),
    },
    {
        slug: "layout-switcher",
        section: "Animations",
        group: "Layouts",
        title: "Layout switcher",
        description: "Card lists that animate between a list and a grid view with a staggered transition.",
        load: () => import("./layout-switcher/index.ts"),
    },
    {
        slug: "text-effects",
        section: "Animations",
        group: "Visuals",
        title: "Text effects",
        description: "Animated text effects for headings and inline words, from spoilers and scrambles to waves, 3D flips and a typewriter.",
        load: () => import("./text-effects/index.ts"),
    },
    {
        slug: "background-animations",
        section: "Animations",
        group: "Visuals",
        title: "Backgrounds",
        description: "Interactive canvas backgrounds that react to the pointer, for hero sections and landing pages.",
        load: () => import("./background-animations/index.ts"),
    },
    {
        slug: "search-placeholder",
        section: "Animations",
        group: "Visuals",
        title: "Search placeholder",
        description: "Search inputs whose placeholder cycles through hints with fade, typewriter, flip or slide animations.",
        load: () => import("./search-placeholder/index.ts"),
    },
    {
        slug: "chat-screen",
        section: "Animations",
        group: "Visuals",
        title: "Chat screen",
        description: "Animated chat threads with a message input, emoji reactions and file attachments, ready to wire to your own messages and backend.",
        load: () => import("./chat-screen/index.ts"),
    },
    {
        slug: "dropdown-animations",
        section: "Animations",
        group: "Visuals",
        title: "Dropdowns",
        description: "Dropdown menus whose items animate in one after another, with a blur-in or a drop-from-above entrance.",
        load: () => import("./dropdown-animations/index.ts"),
    },
    {
        slug: "mouse-navigations",
        section: "Animations",
        group: "Visuals",
        title: "Mouse navigation",
        description: "Overflowing tab bars you move through with the mouse wheel or by dragging, with an animated panel for the active tab.",
        load: () => import("./mouse-navigations/index.ts"),
    },
    {
        slug: "gallery-view",
        section: "Animations",
        group: "Visuals",
        title: "Gallery view",
        description: "An image grid that blurs the other images on hover and opens the picked image with its details in a dialog.",
        load: () => import("./gallery-view/index.ts"),
    },
];
