import {useEffect, useRef, useState} from 'react';

// react icons
import {LuCheck, LuLoader2, LuPaintbrush} from "react-icons/lu";

// ai api
import {generateTailwindConfig} from "@helpers/genaiAPI.ts";

// response panel
import AIResponseSidebar from './AIResponseSidebar.tsx';

// framer motion
import {AnimatePresence, motion} from "framer-motion";

const INCLUDED = [
    "Colors with light and dark values",
    "Font families",
    "Extra spacing and border radius steps",
    "Shadows, breakpoints and z-index",
    "Transitions and a scrollbar-hide utility",
];

const Generator = () => {
    const [prompt, setPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [error, setError] = useState('');
    const [inputError, setInputError] = useState('');
    const [codes, setCodes] = useState('');
    const [lastPrompt, setLastPrompt] = useState('');
    const [placeholderIndex, setPlaceholderIndex] = useState(0);
    const [typingText, setTypingText] = useState('');
    const outputRef = useRef(null);

    const [promtFocused, setPromptFocused] = useState(false)

    const placeholders = [
        "E-commerce website",
        "Modern blog website",
        "Developer portfolio website",
        "Agency dashboard"
    ];

    useEffect(() => {
        let currentText = '';
        let currentIndex = 0;
        let typingInterval;
        let currentPlaceholder = placeholders[placeholderIndex];

        const typeText = () => {
            if (currentIndex < currentPlaceholder.length) {
                currentText += currentPlaceholder[currentIndex];
                setTypingText(currentText);
                currentIndex++;
            } else {
                clearInterval(typingInterval);
                setTimeout(() => {
                    // Start erasing after 2 seconds
                    startErasing();
                }, 2000);
            }
        };

        const startErasing = () => {
            currentIndex = currentText.length;
            typingInterval = setInterval(() => {
                if (currentIndex > 0) {
                    currentText = currentText.slice(0, -1);
                    setTypingText(currentText);
                    currentIndex--;
                } else {
                    clearInterval(typingInterval);
                    setPlaceholderIndex((prev) => (prev + 1) % placeholders.length);
                }
            }, 50);
        };

        typingInterval = setInterval(typeText, 100);

        return () => {
            clearInterval(typingInterval);
        };
    }, [placeholderIndex]);

    const handleGenerateConfig = async () => {
        if (!prompt.trim()) {
            setInputError('Describe your project first, for example "Agency dashboard".');
            return;
        }

        try {
            setInputError('');
            setError('');
            setIsGenerating(true);
            setLastPrompt(prompt.trim());

            // On narrow screens the result sits below the form, so bring it into view.
            if (window.matchMedia('(max-width: 1023px)').matches) {
                requestAnimationFrame(() => outputRef.current?.scrollIntoView({behavior: 'smooth', block: 'start'}));
            }

            const generatedConfig = await generateTailwindConfig(prompt);

            const currentDate = new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            });

            // Add header comment and strip markdown code fences (```css, ```javascript, ```)
            const formattedCode = `
/**
* Generated by @ZenUI Library
* Date: ${currentDate}
*/

${generatedConfig.replace(/```[a-zA-Z]*\n?/g, '').trim()}
      `;

            setCodes(formattedCode);
            setPrompt('');

        } catch (err) {
            setError('The config could not be generated. Check your connection and try again.');
            setCodes('');
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSubmit = (event) => {
        event.preventDefault();
        if (!isGenerating) handleGenerateConfig();
    };

    return (
        <div className="grid gap-5 1024px:grid-cols-[minmax(0,5fr)_minmax(0,7fr)] 1024px:gap-6">
            <section aria-label="Project description" className="panel p-5 shadow-card 640px:p-6">
                <form onSubmit={handleSubmit} noValidate>
                    <label htmlFor="manual-input" className="text-[0.95rem] font-semibold tracking-heading text-ink">
                        Describe your project
                    </label>
                    <p className="mt-1 text-[0.85rem] leading-relaxed text-ink-muted">
                        A type of site plus a mood or brand works well, like "calm fintech dashboard" or "playful
                        kids bookstore".
                    </p>

                    <div className="relative mt-3">
                        <input
                            id="manual-input"
                            type="text"
                            value={prompt}
                            autoComplete="off"
                            aria-invalid={Boolean(inputError)}
                            aria-describedby={inputError ? "prompt-error" : undefined}
                            placeholder={promtFocused ? "Calm fintech dashboard" : ""}
                            onFocus={() => setPromptFocused(true)}
                            onBlur={() => setPromptFocused(false)}
                            onChange={(e) => {
                                setPrompt(e.target.value);
                                setInputError('');
                            }}
                            className="h-11 w-full rounded-[10px] border border-hairline-strong bg-surface px-3.5 text-[0.95rem] text-ink outline-none transition-[border-color,box-shadow] duration-200 placeholder:text-ink-subtle focus:border-accent focus:ring-2 focus:ring-accent/20 focus-visible:outline-none aria-[invalid=true]:border-red-500"
                        />
                        <AnimatePresence>
                            {(!promtFocused && !prompt) && (
                                <motion.span
                                    aria-hidden="true"
                                    initial={{opacity: 0}}
                                    animate={{opacity: 1}}
                                    exit={{opacity: 0}}
                                    transition={{duration: 0.2}}
                                    className="pointer-events-none absolute inset-y-0 left-3.5 flex items-center text-[0.95rem] text-ink-subtle"
                                >
                                    {typingText}
                                    <motion.span
                                        className="ml-px inline-block h-[1.1em] w-px bg-ink-subtle"
                                        animate={{opacity: [0, 1, 0]}}
                                        transition={{duration: 0.8, repeat: Infinity}}
                                    />
                                </motion.span>
                            )}
                        </AnimatePresence>
                    </div>
                    {inputError && (
                        <p id="prompt-error" role="alert" className="mt-2 text-[0.83rem] text-red-600 dark:text-red-400">
                            {inputError}
                        </p>
                    )}

                    <button
                        type="submit"
                        disabled={isGenerating}
                        aria-busy={isGenerating}
                        className="btn-accent mt-5 w-full 425px:w-auto"
                    >
                        {isGenerating ? <LuLoader2 className="size-4 animate-spin"/> : <LuPaintbrush className="size-4"/>}
                        {isGenerating ? "Generating" : "Generate config"}
                    </button>
                </form>

                <div className="mt-7 border-t border-hairline pt-5">
                    <h2 className="text-[0.85rem] font-semibold tracking-heading text-ink">What the theme includes</h2>
                    <ul className="mt-3 space-y-2">
                        {INCLUDED.map((item) => (
                            <li key={item} className="flex items-start gap-2.5 text-[0.85rem] text-ink-muted">
                                <LuCheck className="mt-[3px] size-3.5 shrink-0 text-accent-strong"/>
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
            </section>

            <div ref={outputRef} className="flex scroll-mt-24 flex-col">
                <AIResponseSidebar
                    codes={codes}
                    isGenerating={isGenerating}
                    error={error}
                    prompt={lastPrompt}
                    onRetry={handleGenerateConfig}
                    canRetry={Boolean(prompt.trim())}
                />
            </div>
        </div>
    );
};

export default Generator;
