export const allComponents = [
    {
        title: "input",
        image: "https://i.ibb.co.com/jPCQKgcH/input-text.png",
        url: "/components/input-text",
        groupName: "input",
    },
    {
        title: "textarea",
        image: "https://i.ibb.co.com/ZRghZbMJ/textarea.png",
        url: "/components/input-textarea",
        groupName: "input",
    },
    {
        title: "switch",
        image: "https://i.ibb.co.com/LDCKbF21/switch.png",
        url: "/components/input-switch",
        groupName: "input",
    },
    {
        title: "radio",
        image: "https://i.ibb.co.com/nqD4JshN/radio.png",
        url: "/components/input-radio",
        groupName: "input",
    },
    {
        title: "Number Input",
        image: "https://i.ibb.co.com/C33ScG8L/number-input.png",
        url: "/components/input-number",
        groupName: "input",
    },
    {
        title: "Checkbox",
        image: "https://i.ibb.co.com/qL7BYzLh/checkbox.png",
        url: "/components/input-checkbox",
        groupName: "input",
    },
    {
        title: "Strong Password",
        image: "https://i.ibb.co.com/tp47bwCk/password.png",
        url: "/components/strong-password",
        groupName: "input",
    },
    {
        title: "Input Range",
        image: "https://i.ibb.co.com/G3csw7Gq/slider.png",
        url: "/components/input-range",
        groupName: "input",
    },
    {
        title: "OTP Input",
        image: "https://i.ibb.co.com/9HBV57H9/otp-input.png",
        url: "/components/otp-input",
        groupName: "input",
    },
    {
        title: "file upload",
        image: "https://i.ibb.co.com/1t3m2dsx/file-upload.png",
        url: "/components/input-file",
        groupName: "input",
    },
    {
        title: "primary button",
        image: "https://i.ibb.co.com/XZMzMc3x/auth-button.png",
        url: "/components/normal-button",
        groupName: "button",
    },
    {
        title: "Auth Button",
        image: "https://i.ibb.co.com/XZMzMc3x/auth-button.png",
        url: "/components/auth-buttons",
        groupName: "button",
    },
    {
        title: "Dropdown Button",
        image: "https://i.ibb.co.com/F4Jz89h8/dropdown-button.png",
        url: "/components/dropdown-button",
        groupName: "button",
    },
    {
        title: "animated button",
        image: "https://i.ibb.co.com/XZMzMc3x/auth-button.png",
        url: "/components/animated-button",
        groupName: "button",
    },
    {
        title: "chip",
        image: "https://i.ibb.co.com/Sh8wRfS/chip.png",
        url: "/components/chip",
        groupName: "navigation",
    },
    {
        title: "Timer",
        image: "https://i.ibb.co.com/zWhdyyw9/timer.png",
        url: "/components/timer",
        groupName: "navigation",
    },
    {
        title: "Progress Bar",
        image: "https://i.ibb.co.com/spL7Mj6S/progress-bar.png",
        url: "/components/progress-bar",
        groupName: "navigation",
    },
    {
        title: "breadcrumb",
        image: "https://i.ibb.co.com/0yF7w2Vh/breadcrumb.png",
        url: "/components/breadcrumb",
        groupName: "navigation",
    },
    {
        title: "Rating",
        image: "https://i.ibb.co.com/5X02YvpF/star.png",
        url: "/components/rating",
        groupName: "navigation",
    },
    {
        title: "stepper",
        image: "https://i.ibb.co.com/rYktPY2/stepper.png",
        url: "/components/stepper",
        groupName: "navigation",
    },
    {
        title: "tab",
        image: "https://i.ibb.co.com/15SFDvL/tabs.png",
        url: "/components/tabs",
        groupName: "navigation",
    },
    {
        title: "modal",
        image: "https://i.ibb.co.com/215fVcPy/tabs-1.png",
        url: "/components/modal",
        groupName: "navigation",
    },
    {
        title: "pagination",
        image: "https://i.ibb.co.com/HfHxj95Z/pagination.png",
        url: "/components/pagination",
        groupName: "navigation",
    },
    {
        title: "tooltip",
        image: "https://i.ibb.co.com/W4bwRntD/tooltip.png",
        url: "/components/tooltip",
        groupName: "data_display",
    },
    {
        title: "badge",
        image: "https://i.ibb.co.com/KjWkrhsy/badge.png",
        url: "/components/badge",
        groupName: "data_display",
    },
    {
        title: "Table",
        image: "https://i.ibb.co.com/4RHQR95k/table.png",
        url: "/components/table",
        groupName: "data_display",
    },
    {
        title: "Timeline",
        image: "https://i.ibb.co.com/MxRkbhn8/timeline.png",
        url: "/components/timeline",
        groupName: "data_display",
    },
    {
        title: "alert message",
        image: "https://i.ibb.co.com/fGV0yyRH/alert-message.png",
        url: "/components/alert-message",
        groupName: "feedback",
    },
    {
        title: "skeleton",
        image: "https://i.ibb.co.com/Hf2MzTpx/skeleton.png",
        url: "/components/skeleton",
        groupName: "feedback",
    },
    {
        title: "Tree Dropdown",
        image: "https://i.ibb.co.com/tpMgwyXd/tree-dropdown.png",
        url: "/components/tree-dropdown",
        groupName: "feedback",
    },
    {
        title: "loader",
        image: "https://i.ibb.co.com/twPgxrzF/loading.png",
        url: "/components/loader",
        groupName: "feedback",
    },
    {
        title: "accordion",
        image: "https://i.ibb.co.com/d02kpWBp/accordion.png",
        url: "/components/according",
        groupName: "surface",
    },
    {
        title: "card",
        image: "https://i.ibb.co.com/TB8ZmMSJ/card.png",
        url: "/components/cards",
        groupName: "surface",
    },
    {
        title: "Drag & Drop",
        image: "https://i.ibb.co.com/LDDRVCcS/drag-drop.png",
        url: "/components/drag-and-drop",
        groupName: "surface",
    },
    {
        title: "appbar",
        image: "https://i.ibb.co.com/G4h1dSpz/app-bar.png",
        url: "/components/appbar",
        groupName: "surface",
    },
    {
        title: "image gallery",
        image: "https://i.ibb.co.com/jZ8Pkbtz/image-gellery.png",
        url: "/components/image-gallery",
        groupName: "surface",
    },
];
