export const DevContributorsData = [
    {
        name: 'Raihan Uddin Tuhin\n',
        title: 'Web Developer',
        image: 'https://avatars.githubusercontent.com/u/98041657?v=4',
        linkedinLink: 'https://www.linkedin.com/in/raihan-uddin-tuhin-7a200125a/',
        twitterLink: '',
        githubLink: 'https://github.com/Tuhin35',
        website: 'https://portfolio-final-gamma-six.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Rahamtullah sheikh',
        title: 'Software Engineer',
        image: 'https://avatars.githubusercontent.com/u/76489436?v=4',
        linkedinLink: 'https://www.linkedin.com/in/rahamtullah-sheikh-792497205/',
        twitterLink: 'https://x.com/Rahamtullah123',
        githubLink: 'https://github.com/rhm856591',
        website: 'https://rahamtullah-sheikh.netlify.app/',
        zenuiHero: false,
    },
    {
        name: 'Danish Kamal',
        title: 'Frontend Developer',
        image: 'https://avatars.githubusercontent.com/u/46997504?v=4',
        linkedinLink: 'https://www.linkedin.com/in/danishzayan/',
        twitterLink: '',
        githubLink: 'https://github.com/danishzayan',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'Eshwar S Devaramane',
        title: 'Software Engineer',
        image: 'https://i.ibb.co.com/WfP5nhm/1712361854052.jpg',
        linkedinLink: 'https://www.linkedin.com/in/eshwar-sdev/',
        twitterLink: '',
        githubLink: 'https://github.com/eshward95/',
        website: 'https://bento.me/e-sdev',
        zenuiHero: false,
    },
]