export const DevContributorsData = [
    {
        name: 'Raihan Uddin Tuhin\n',
        title: 'Web Developer',
        certificate: 'Raihan',
        image: 'https://avatars.githubusercontent.com/u/98041657?v=4',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/Tuhin35',
        website: 'https://portfolio-final-gamma-six.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Rahamtullah sheikh',
        title: 'Software Engineer',
        certificate: 'Rahamtullah',
        image: 'https://avatars.githubusercontent.com/u/76489436?v=4',
        linkedinLink: 'https://www.linkedin.com/in/rahamtullah-sheikh-792497205/',
        twitterLink: 'https://x.com/Rahamtullah123',
        githubLink: 'https://github.com/rhm856591',
        website: 'https://rahamtullah-sheikh.netlify.app/',
        zenuiHero: false,
    },
    {
        name: 'Danish Kamal',
        title: 'Frontend Developer',
        certificate: 'Danish',
        image: 'https://avatars.githubusercontent.com/u/46997504?v=4',
        linkedinLink: 'https://www.linkedin.com/in/danishzayan/',
        twitterLink: '',
        githubLink: 'https://github.com/danishzayan',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'Eshwar S Devaramane',
        title: 'Software Engineer',
        certificate: 'Eshwar',
        image: 'https://i.ibb.co.com/WfP5nhm/1712361854052.jpg',
        linkedinLink: 'https://www.linkedin.com/in/eshwar-sdev/',
        twitterLink: '',
        githubLink: 'https://github.com/eshward95/',
        website: 'https://bento.me/e-sdev',
        zenuiHero: false,
    },
    {
        name: 'phuoctaiismee',
        title: 'Web Developer',
        certificate: 'phuoctaiismee',
        image: 'https://avatars.githubusercontent.com/u/113773744?v=4',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/phuoctaiismee',
        website: '',
        zenuiHero: false,
    },
    {
        name: 'MD.Asif Ullah',
        title: 'Web Developer',
        certificate: 'Asif',
        image: 'https://i.ibb.co.com/YNSYsPL/122894322.jpg',
        linkedinLink: 'https://www.linkedin.com/in/DevMdAsif',
        twitterLink: 'https://x.com/DevMdAsif',
        githubLink: 'https://github.com/md-asif-ullah',
        website: '',
        zenuiHero: false,
    },
    {
        name: 'Fabian Ajokubi',
        title: 'Frontend Developer',
        certificate: 'Fabian',
        image: 'https://i.ibb.co.com/DMxRHBd/1704506313487.jpg',
        linkedinLink: 'https://www.linkedin.com/in/fabiconcept/?originalSubdomain=ng',
        twitterLink: '',
        githubLink: 'https://github.com/fabiconcept',
        website: 'https://fabiconcept.online/',
        zenuiHero: false,
    },
    {
        name: 'Hoang Nguyen',
        title: 'Web Developer',
        certificate: 'Hoang',
        image: 'https://i.ibb.co.com/VwfFxF3/67743418.jpg',
        linkedinLink: 'https://www.linkedin.com/in/hoang-nguyen-876a12257/',
        twitterLink: 'https://x.com/akirad836',
        githubLink: 'https://github.com/Zysd836',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'Misbahul Alam',
        title: 'Full-stack Web Developer',
        certificate: 'Misbahul',
        image: 'https://avatars.githubusercontent.com/u/88716007?v=4',
        linkedinLink: 'https://www.linkedin.com/in/misbahul-alam',
        twitterLink: '',
        githubLink: 'https://github.com/misbahul-alam',
        website: 'https://misbahulalam.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Mohammad Shahnwaz',
        title: 'Full-stack Web Developer',
        certificate: 'Shahnwaz',
        image: 'https://i.ibb.co.com/pwqnW7M/34994498.jpg',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/Shahnwazh170',
        website: 'https://shahnwazh170.github.io/',
        zenuiHero: false,
    },
    {
        name: 'Fazly Alahi\n',
        title: 'React Developer',
        certificate: 'Fazly',
        image: 'https://i.ibb.co.com/6cKkv925/Te8-Aj-GI-400x400.jpg',
        linkedinLink: 'https://www.linkedin.com/in/fazlyalahiru/',
        twitterLink: 'https://x.com/fazlyalahiru',
        githubLink: 'https://github.com/fazlyalahi01',
        website: 'https://fazly-alahi.netlify.app/',
        zenuiHero: false,
    },
    {
        name: 'Mohiul Islam',
        title: 'Full Stack Web Developer',
        certificate: 'Mohiul',
        image: 'https://avatars.githubusercontent.com/u/68007928?v=4',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/mohiulislam',
        website: '',
        zenuiHero: true,
    },
    {
        name: 'codemine24',
        title: 'Web Developer',
        certificate: 'codemine24',
        image: 'https://i.ibb.co.com/fdSvvkYp/pngtree-person-gray-photo-placeholder-man-silhouette-on-gray-background-png-image-4847624.png',
        linkedinLink: '',
        twitterLink: '',
        githubLink: 'https://github.com/codemine24',
        website: '',
        zenuiHero: false,
    },
    {
        name: 'Novodip Mondal',
        title: 'Frontend Developer',
        certificate: 'novodip_mondal',
        image: 'https://i.ibb.co.com/jPynRqhX/120156959.jpg',
        linkedinLink: 'https://www.linkedin.com/in/novodip/',
        twitterLink: '',
        githubLink: 'https://github.com/Novo1999',
        website: 'https://novodip.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Yeakin Iqra',
        title: 'Software Engineer',
        certificate: 'yeakin_iqra',
        image: 'https://i.ibb.co.com/v6N0JJzF/108855634.jpg',
        linkedinLink: 'https://www.linkedin.com/in/nazmul-yeakin-iqra-975206344/',
        twitterLink: '',
        githubLink: 'https://github.com/yeakiniqra',
        website: 'https://yeakiniqra.com/',
        zenuiHero: false,
    },
    {
        name: 'Md Shakil Hossain',
        title: 'FullStack Engineer',
        certificate: 'shakil_hossain',
        image: 'https://i.ibb.co.com/KjGQPZtD/108464347.png',
        linkedinLink: 'https://www.linkedin.com/in/devshakilh/',
        twitterLink: 'https://x.com/devshakilh',
        githubLink: 'https://github.com/devshakilh',
        website: 'https://devshakilh.netlify.app/',
        zenuiHero: false,
    },
    {
        name: 'Faridul Haque Murshed',
        title: 'Web Developer',
        certificate: 'faridul_haque',
        image: 'https://i.ibb.co.com/KpdyCnMs/1655659208355.jpg',
        linkedinLink: 'https://www.linkedin.com/in/faridulhaquemurshed/',
        githubLink: 'https://github.com/faridulhaque',
        website: 'https://my-portfolio-v4.vercel.app/',
        zenuiHero: false,
    },
    {
        name: 'Yeakin Iqra',
        title: 'Software Engineer',
        certificate: 'yeakin_iqra',
        image: 'https://i.ibb.co.com/tTzF87yN/108855634.jpg',
        linkedinLink: 'https://www.linkedin.com/in/nazmul-yeakin-iqra-975206344/',
        githubLink: 'https://github.com/yeakiniqra',
        website: 'https://yeakiniqra.me/',
        zenuiHero: false,
    },
    {
        name: 'Murad',
        title: 'Software Engineer',
        certificate: 'murad',
        image: 'https://i.ibb.co.com/DPqRp7jt/72880355.jpg',
        twitterLink: 'https://x.com/murad_dev',
        githubLink: 'https://github.com/mozaddedalfeshani',
        website: 'https://imurad.me/',
        zenuiHero: true,
    },
]